Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/hpc/hers_en/fsimoes/jPCA/JaccardChunks/mijs/eq_pos_count_1.rds', probable reason 'No such file or directory'
Execution halted

real	0m1.127s
user	0m0.176s
sys	0m0.083s
